version: '3.8'
services:
  db:
    container_name: wharp-postgis-${SERVER}
    image: postgis/postgis:14-3.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
      PGPORT: ${PGPORT}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_DATABASE_NAME}' ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${PGPORT}:${PGPORT}
    networks:
      - geodata-network
    command: sh -c "/usr/local/bin/docker-entrypoint.sh postgres"
    volumes:
      - .${PGDATA}:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d

  pgAdmin:
    # wharp-db.hextra.dev
    container_name: wharp-pgadmin-${SERVER}
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGPORT: ${PGPORT}
    networks:
      - geodata-network
    ports:
      - '8081:80'
    depends_on:
      - db

networks:
   geodata-network:
      name: geodata
      driver: bridge
      ipam:
         driver: default
         config:
            - subnet: 192.168.199.0/24

volumes:
  db:
    driver: local
